### ISSUE TITLE
MR Graph wrong on Y axis

### ISSUE THREAD

**Issue by ilidrissireda** [alanoliveira/sfbuff#68]
![Screenshot (206)](https://github.com/user-attachments/assets/257558a7-3814-4b09-87b0-242b9c5578ca)

It's like this for a lot more data points, the Y axis is all over the place.

**Comment by alanoliveira** [comment]
Hello,
The points are actually correct.
You need to sum the value with the the variation.
For example, on the last point, the value is "1294 MR + 7", so it is 1301.

But thinking better now I agree it is confuse.
I will change it to show the total value.
